### ISSUE TITLE
"Use Case" Examples are leaking domain objects (entities)

### ISSUE THREAD

**Issue by eladchen** [mattia-battiston/clean-architecture-example#7]
Hi,

In his book uncle bob writes that entities should not be passed to use cases or returned from use cases, which is clearly not the case in this repo.

I was wondering if that is intentional, and if so, why?

From what I understand, A use case input and output should be a DTO, thus preventing upper layers from ever having access to an object two layers down.

**Comment by mattia-battiston** [comment]
Hi @eladchen 

I might have to read that part again, to be honest I've never seen it as a problem. I might have misunderstood unclebob, but I see a use case as the owner of the business logic, so it makes sense for me to use domain objects.

I guess there is an edge case when a use case needs more information than an entity can hold, or needs to return a complex data structure. In that case it makes to create DTOs for input or output. But I would do it for convenience, rather than as a rule.

Does that make sense? This is just my interpretation by the way, it's possible that unclebob disagrees on this one.

Mattia
